"use client";
import { useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { createOrbitPost } from "@/services/orbit";
import { validatePost } from "../orbit.validation";
import { ORBIT_MAX_IMAGES, ORBIT_MAX_POST_LENGTH } from "../orbit.constants";

export function OrbitComposer({ userId, onCreated }: { userId: string; onCreated: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [content, setContent] = useState(""); const [files, setFiles] = useState<File[]>([]); const [status, setStatus] = useState(""); const input = useRef<HTMLInputElement>(null);
  async function submit() { const validation = validatePost(content, files); if (validation) { setStatus(validation); return; } setStatus("Publishing…"); try { await createOrbitPost(createClient(), userId, content, files, []); setContent(""); setFiles([]); setStatus(""); setOpen(false); await onCreated(); } catch (error) { setStatus(error instanceof Error ? error.message : "We couldn't publish your post."); } }
  return <section className="rounded-2xl border border-surface-200 bg-surface-100/60 p-4">{!open ? <button onClick={() => setOpen(true)} className="flex w-full items-center gap-3 text-left text-sm text-slate-400"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-campus-500/20 text-campus-400">✦</span><span>Share something with your campus…</span></button> : <div className="space-y-3"><textarea autoFocus value={content} onChange={(event) => setContent(event.target.value)} maxLength={ORBIT_MAX_POST_LENGTH} rows={5} placeholder="What's happening on campus?" className="w-full resize-y rounded-xl border border-surface-300 bg-background p-3 text-sm outline-none focus:border-campus-500" aria-label="Post content"/><div className="flex items-center justify-between text-xs text-slate-500"><span>{content.length}/{ORBIT_MAX_POST_LENGTH}</span><button onClick={() => input.current?.click()} className="rounded-lg border border-surface-300 px-3 py-2 hover:border-campus-500">📷 Add images</button><input ref={input} type="file" accept="image/*" multiple hidden onChange={(event) => setFiles(Array.from(event.target.files ?? []))}/></div>{files.length > 0 && <p className="text-xs text-slate-400">{files.length} image{files.length === 1 ? "" : "s"} selected (max {ORBIT_MAX_IMAGES})</p>}{status && <p role="status" className="text-xs text-amber-300">{status}</p>}<div className="flex gap-2"><button onClick={() => { setOpen(false); setStatus(""); }} className="flex-1 rounded-xl border border-surface-300 px-3 py-2 text-sm">Cancel</button><button onClick={submit} disabled={status === "Publishing…"} className="flex-1 rounded-xl bg-campus-500 px-3 py-2 text-sm font-bold text-black disabled:opacity-50">Post</button></div></div>}</section>;
}
