"use client";
import { useState } from "react";
import type { OrbitPost } from "../orbit.types";
import { displayName, formatOrbitTime, initials } from "../orbit.utils";
import { createClient } from "@/lib/supabase/client";
import { deleteOrbitPost, reportOrbitPost, toggleOrbitLike, toggleOrbitSave } from "@/services/orbit";
import { validateReportReason } from "../orbit.validation";

export function OrbitPostCard({ post, userId, onChangeAction, onCommentAction }: { post: OrbitPost; userId: string; onChangeAction: (post: OrbitPost) => void; onCommentAction: () => void }) {
  const [busy, setBusy] = useState(false); const name = displayName(post.author, post.poster_name ?? undefined); const supabase = createClient();
  async function action(kind: "like" | "save") { if (busy) return; setBusy(true); const next = kind === "like" ? !post.liked : !post.saved; onChangeAction({ ...post, ...(kind === "like" ? { liked: next, like_count: post.like_count + (next ? 1 : -1) } : { saved: next }) }); try { if (kind === "like") await toggleOrbitLike(supabase, post.id, userId, post.liked); else await toggleOrbitSave(supabase, post.id, userId, post.saved); } catch { onChangeAction(post); } finally { setBusy(false); } }
  async function report() { const reason = window.prompt("Why are you reporting this post? Use: spam, harassment, inappropriate, misinformation, or other.", "other")?.trim().toLowerCase() ?? ""; const validation = validateReportReason(reason); if (validation) { if (reason) window.alert(validation); return; } try { await reportOrbitPost(supabase, post.id, reason); window.alert("Report submitted."); } catch (error) { window.alert(error instanceof Error ? error.message : "Report failed."); } }
  async function remove() { if (!window.confirm("Delete this post?")) return; try { await deleteOrbitPost(supabase, post.id); onChangeAction({ ...post, status: "deleted" }); } catch { window.alert("We couldn't delete that post."); } }
  return <article className="rounded-2xl border border-surface-200 bg-surface-100/60 p-4"><header className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-campus-500/20 font-semibold text-campus-300">{post.author?.avatar_url ? <img src={post.author.avatar_url} alt={`${name} profile`} className="h-full w-full object-cover" loading="lazy"/> : initials(name)}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{name}</p><p className="text-xs text-slate-500">{post.school_tag ?? post.author?.university ?? "Campus"} · {formatOrbitTime(post.created_at)}{post.edited_at ? " · edited" : ""}</p></div><button onClick={report} className="rounded-lg px-2 py-1 text-xs text-slate-500 hover:bg-surface-200" aria-label="Report post">•••</button></header>{post.content && <p className="mt-4 whitespace-pre-wrap break-words text-sm leading-6 text-slate-200">{post.content}</p>}{post.images && post.images.length > 0 && <div className={`mt-4 grid gap-1 overflow-hidden rounded-xl ${post.images.length === 1 ? "grid-cols-1" : "grid-cols-2"}`}>{post.images.map((image, index) => <img key={`${image}-${index}`} src={image} alt={`Post image ${index + 1}`} loading="lazy" className="aspect-square h-full w-full object-cover" onError={(event) => { event.currentTarget.style.display = "none"; }}/>)}</div>}<footer className="mt-4 flex gap-2 border-t border-surface-200 pt-3 text-xs"><button disabled={busy} onClick={() => action("like")} className={`rounded-lg px-3 py-2 hover:bg-surface-200 ${post.liked ? "text-campus-400" : "text-slate-400"}`}>♥ {post.like_count}</button><button type="button" onClick={onCommentAction} className="rounded-lg px-3 py-2 text-slate-400 hover:bg-surface-200">💬 {post.comment_count}</button><button disabled={busy} onClick={() => action("save")} className={`rounded-lg px-3 py-2 hover:bg-surface-200 ${post.saved ? "text-amber-300" : "text-slate-400"}`}>🔖 {post.saved ? "Saved" : "Save"}</button>{post.poster_id === userId && <button onClick={remove} className="ml-auto rounded-lg px-3 py-2 text-slate-500 hover:bg-surface-200">Delete</button>}</footer></article>;
}
