export const STUDY_CONSTANTS = {
  COURSE_PAGE_SIZE: 20,
  RESOURCE_PAGE_SIZE: 20,
  SEARCH_DEBOUNCE_MS: 300,
  TRIBE_PAGE_SIZE: 20,
  TRIBE_POST_PAGE_SIZE: 20,
  TRIBE_NAME_MIN_LENGTH: 2,
  TRIBE_NAME_MAX_LENGTH: 80,
  TRIBE_DESCRIPTION_MAX_LENGTH: 500,
  TRIBE_POST_MAX_LENGTH: 2000,
} as const;
